// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh-evY9NXsaBAwFevRPXhOO7jan2vKco8',
    appId: '1:387428609843:web:998956a81f606d63b65846',
    messagingSenderId: '387428609843',
    projectId: 'chat-app-5a724',
    authDomain: 'chat-app-5a724.firebaseapp.com',
    storageBucket: 'chat-app-5a724.appspot.com',
    measurementId: 'G-36E5NKPDPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Vah20w8xyMrsnYGTfwoZiNq7vIhO6CU',
    appId: '1:387428609843:android:7bbaa0477c45bf28b65846',
    messagingSenderId: '387428609843',
    projectId: 'chat-app-5a724',
    storageBucket: 'chat-app-5a724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADo1p5aHY5aFX-Zf3rGSAKlfnKIWsvopY',
    appId: '1:387428609843:ios:477b7bad30299b97b65846',
    messagingSenderId: '387428609843',
    projectId: 'chat-app-5a724',
    storageBucket: 'chat-app-5a724.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADo1p5aHY5aFX-Zf3rGSAKlfnKIWsvopY',
    appId: '1:387428609843:ios:d3bc84fe627dda9bb65846',
    messagingSenderId: '387428609843',
    projectId: 'chat-app-5a724',
    storageBucket: 'chat-app-5a724.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
